version: '3.8'

services:
  frontend:
    build:
      context: ./apartment-listing-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map Nginx (frontend) to localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: appartment-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: